### ISSUE TITLE
Modal tests are failing with 2.0.0-M5

### ISSUE THREAD

**Issue by eximius313** [l0rdn1kk0n/wicket-bootstrap#683] opened 2017-06-08 09:52 UTC
Here is the showcase:
[wicket-showcase-windowTests.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1060598/wicket-showcase-windowTests.zip)

Steps to reproduce:
* With version ```0.10.6``` invoke ```./gradlew clean build``` -> Tests pass
* Edit ```build.gradle```, uncomment line 17 and comment 16
* With version ```2.0.0-M5``` invoke ```./gradlew clean build``` -> Tests fail

**Comment by martin-g** [comment] 2017-06-08 10:19
Any help is welcome!
I don't much time and dealing with Gradle projects consumes a lot of my time ... :-/

**Comment by eximius313** [comment] 2017-06-08 10:21
But this is almost the same showcase as previous one.
I spent some time on this one, but I have *no idea* why tests are failing (and this is probably change of one line - like in previos bugs)

**Comment by martin-g** [comment] 2017-06-08 10:25
At the moment I think it would be much easier if you paste me the stacktrace than dealing with Gradle, Lombok, Spring, Hibernate, ...
This is why I said that Wicket Quickstart based project would be the best!

**Comment by eximius313** [comment] 2017-06-08 10:32
Although I have Markup file, it throws:
```
org.apache.wicket.markup.MarkupNotFoundException: Failed to find markup file associated. Window: [Window [Component id = window]]
    at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.getMarkup(AssociatedMarkupSourcingStrategy.java:99)
    at org.apache.wicket.MarkupContainer.getMarkup(MarkupContainer.java:502)
    at org.apache.wicket.Component.getMarkup(Component.java:756)
    at org.apache.wicket.Component.internalRender(Component.java:2360)
    at org.apache.wicket.Component.render(Component.java:2323)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1453)
    at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1653)
    at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1628)
    at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:797)
    at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
    at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
    at org.apache.wicket.Component.internalRenderComponent(Component.java:2595)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1592)
    at org.apache.wicket.Component.internalRender(Component.java:2395)
    at org.apache.wicket.Component.render(Component.java:2323)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1453)
    at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1653)
    at org.apache.wicket.Page.onRender(Page.java:857)
    at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:126)
    at org.apache.wicket.Component.internalRender(Component.java:2395)
    at org.apache.wicket.Component.render(Component.java:2323)
    at org.apache.wicket.Page.renderPage(Page.java:987)
    at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
    at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
    at org.apache.wicket.util.tester.BaseWicketTester$LastPageRecordingPageRendererProvider$1.respond(BaseWicketTester.java:2785)
    at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202)
    at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912)
    at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
    at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:283)
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
    at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:711)
    at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:650)
    at org.apache.wicket.util.tester.BaseWicketTester.startPage(BaseWicketTester.java:877)
    at org.apache.wicket.util.tester.BaseWicketTester.startPage(BaseWicketTester.java:894)
    at org.apache.wicket.util.tester.BaseWicketTester.startComponentInPage(BaseWicketTester.java:1480)
    at org.apache.wicket.util.tester.BaseWicketTester.startComponentInPage(BaseWicketTester.java:1400)
    at com.showcase.gui.window.WindowTest.setup(WindowTest.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by eximius313** [comment] 2017-06-08 10:34
I'm going to remove Lombok completly from my showcase so it would be easier for you.
If it's about Spring/Hibernate - there are just dependencies that are automaticaly downloaded, so they shouldn't bother you

**Comment by eximius313** [comment] 2017-06-08 10:36
Here is the showcase without lombok: 
[wicket-showcase-windowTests.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1060705/wicket-showcase-windowTests.zip)

**Comment by mikey75** [comment] 2017-06-08 11:05
Correct me if I am wrong but I think you need to have markup in the correct location (together with *.java file). Your markup is in resources, and unless you specify non-default markup sourcing strategy, it won't work.

**Comment by eximius313** [comment] 2017-06-08 11:18
I have it. How else tests would pass with 0.10.6 version?

**Comment by martin-g** [comment] 2017-06-08 11:38
The .html should be next to `.class`, not to `.java`, so if Gradle does its job then it should be OK.

**Comment by eximius313** [comment] 2017-06-08 11:42
Tested on Gradle, Eclipse and IDEA.
All three behave the same.
The *only one thing* that changes is version from ```0.10.6``` to ```2.0.0-M5```

**Comment by mikey75** [comment] 2017-06-08 11:47
Yeah, martin-g, you're right. Sorry for misleading :)

**Comment by martin-g** [comment] 2017-06-15 18:28
For ~20 mins I cannot find a way to setup this project to build in IDEA.
Now `import com.showcase.model.AbstractEntity;` cannot be resolved in `com.showcase.gui.window.WindowTest`...

**Comment by martin-g** [comment] 2017-06-15 18:39
Finally I was able to start the test!
But only with Wicket 8.0.0-M6. I am not able to tell it to use -SNAPSHOT still.
The problem disappears if I remove `spy(rawWindow)` and use non-mock Wicket component.

**Comment by martin-g** [comment] 2017-06-15 18:47
The problem is that the Spy is added as a child to the test page, so it has a parent.
But the real/raw component doesn't have a parent page and it fails to find its markup type.
I don't see how this may work with `0.10.6` but I also don't have desire to fight with Gradle. Definitely you should not use WB `0.10.6` with Wicket `8.x`!

**Closed by martin-g** 2017-06-15 18:47 UTC
