### ISSUE TITLE
link to demo

### ISSUE THREAD

**Issue by UlrichKnaack** [l0rdn1kk0n/wicket-bootstrap#710] opened 2017-11-22 07:35 UTC
Please update link to demo site (http://coding.teliclab.info/wicket-7.x ) in the header section of the github page

**Comment by martin-g** [comment] 2017-11-22 07:56
Duplicate of https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/706

**Closed by martin-g** 2017-11-22 07:56 UTC
