### ISSUE TITLE
2.0.0-M8 DependencyResolutionException

### ISSUE THREAD

**Issue by francois92** [l0rdn1kk0n/wicket-bootstrap#720] opened 2018-03-02 17:57 UTC
I got this error while using with 2.0.0-M8

DependencyResolutionException: 

Could not resolve dependencies 
The following artifacts could not be resolved: 

de.agilecoders.wicket:jquery-selectors:jar:2.0.0-M5, 
de.agilecoders.wicket.webjars:wicket-webjars:jar:2.0.5: 

Could not find artifact de.agilecoders.wicket:jquery-selectors:jar:2.0.0-M5 in wicketstuff-core-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

François

**Comment by martin-g** [comment] 2018-03-02 18:05
The is an issue for this already.
OSS Sonatype is broken or something.

**Comment by martin-g** [comment] 2018-03-03 12:03
Duplicate of #719

**Closed by martin-g** 2018-03-03 12:03 UTC
